#!/usr/bin/env node
// scripts/sync-agents.mjs
// Regenerates agents/<tier>.md from tiers.json. Agent files are static in
// zcode (no runtime registration hook like opencode's config), so tier →
// model / thoughtLevel / maxTurns / tools / prompt live in committed files
// that this script renders from the single source of truth.
//
// Usage: node scripts/sync-agents.mjs [--preset <name>]
//   --preset   which preset to render (default: activePreset from tiers.json)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { isClaudeModel, CLAUDE_TIER_PREFIX, CLAUDE_ANTI_NARRATION } from "../hooks/scripts/lib/protocol.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const cfg = JSON.parse(readFileSync(join(root, "tiers.json"), "utf-8"));

const argv = process.argv.slice(2);
let presetName = cfg.activePreset;
const presetIdx = argv.indexOf("--preset");
if (presetIdx !== -1 && argv[presetIdx + 1]) {
  presetName = argv[presetIdx + 1];
}

const preset = cfg.presets[presetName];
if (!preset) {
  console.error(`Unknown preset "${presetName}". Available: ${Object.keys(cfg.presets).join(", ")}`);
  process.exit(1);
}

const HEADER = `<!-- GENERATED by scripts/sync-agents.mjs from tiers.json (preset: ${presetName}).
     Do not edit by hand — edit tiers.json and re-run the script. -->`;

function frontmatterValue(v) {
  // zcode's frontmatter parser accepts comma- or space-separated strings for lists.
  return v.join(", ");
}

function renderAgent(tierName, tier) {
  const prompt =
    tier.prompt ??
    cfg.tierPrompts?.[tierName] ??
    `You are @${tierName} — ${tier.description}`;

  // Claude-backed tiers get the adversarial opener (revokes cached Claude-Code
  // explorer priming). GLM tiers pass through untouched.
  const claudePrefix = isClaudeModel(tier.model)
    ? `${CLAUDE_TIER_PREFIX[tierName] ?? ""}\n\n${CLAUDE_ANTI_NARRATION}`
    : "";
  const body = claudePrefix ? `${claudePrefix}\n\n---\n\n${prompt}` : prompt;

  const fm = [
    "---",
    `name: ${tierName}`,
    `description: ${tier.description} Use PROACTIVELY per the Model Delegation Protocol when a dispatch matches: ${tier.whenToUse.join("; ")}.`,
    tier.tools ? `tools: ${frontmatterValue(tier.tools)}` : null,
    `model: ${tier.model}`,
    tier.thoughtLevel ? `thoughtLevel: ${tier.thoughtLevel}` : null,
    tier.maxTurns ? `maxTurns: ${tier.maxTurns}` : null,
    tier.color ? `color: ${tier.color}` : null,
    "---",
  ]
    .filter((l) => l !== null)
    .join("\n");

  return `${HEADER}\n${fm}\n\n${body}\n`;
}

mkdirSync(join(root, "agents"), { recursive: true });
for (const [tierName, tier] of Object.entries(preset)) {
  const out = renderAgent(tierName, tier);
  writeFileSync(join(root, "agents", `${tierName}.md`), out, "utf-8");
  console.log(
    `wrote agents/${tierName}.md  (model=${tier.model}${tier.thoughtLevel ? ` thoughtLevel=${tier.thoughtLevel}` : ""})`,
  );
}
console.log(`\nDone. Restart your zcode session (or open a new one) for the regenerated subagents to load.`);
